// WorldWright Generate Mode slider contract registry.
// Blueprint sources:
// - WORLDWRIGHT_BLUEPRINT_GENERATE_SLIDER_CONTRACT.md
// - WORLDWRIGHT_BLUEPRINT_PLANET_FOUNDATION_LAYERS.md
//
// This file is declarative only. It does not change generation behavior.

export type SliderContractStatus = 'current' | 'target' | 'planned';
export type SliderVisibility = 'basic' | 'advanced' | 'diagnostic-only';

export type SliderContract = {
  readonly id: string;
  readonly label: string;
  readonly status: SliderContractStatus;
  readonly visibility: SliderVisibility;
  readonly currentParamKeys: readonly string[];
  readonly realWorldFunction: string;
  readonly allowedLayers: readonly string[];
  readonly allowedDirectFields: readonly string[];
  readonly shiftedDiagnosticBands: readonly string[];
  readonly neutralMeaning: string;
  readonly lowExtremeMeaning: string;
  readonly highExtremeMeaning: string;
  readonly forbiddenAuthorityRelaxations: readonly string[];
  readonly targetReplacementIds?: readonly string[];
};

const HARD_FORBIDDEN = [
  'plateId -> baseHeight',
  'plateId -> finalColor',
  'crustProvince -> baseHeight',
  'crustProvince -> finalColor',
  'derived recompute -> terrain',
  'final cause sync -> later terrain writer',
] as const;

export const GENERATE_SLIDER_CONTRACTS: readonly SliderContract[] = [
  {
    id: 'STYLE_MODE',
    label: 'Style Mode',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['styleMode'],
    realWorldFunction: 'Selects physical-band strictness and visual/generator personality without changing authority rules.',
    allowedLayers: ['PLANET_PROFILE', 'PHYSICAL_BAND_ADJUSTMENT', 'FINAL_RENDER'],
    allowedDirectFields: ['styleMode'],
    shiftedDiagnosticBands: ['physicalBandWidth', 'terrainReadabilityTolerance', 'biomeClimateTolerance'],
    neutralMeaning: 'EARTHLIKE: strict physical baseline.',
    lowExtremeMeaning: 'Not applicable; style mode is categorical.',
    highExtremeMeaning: 'ALIEN/FANTASY/STYLIZED widen soft physical bands but do not relax authority.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'RESOLUTION',
    label: 'Resolution',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['width', 'height'],
    realWorldFunction: 'Sampling density, not planet physics.',
    allowedLayers: ['GRID_SETUP', 'EXPORT', 'DIAGNOSTICS'],
    allowedDirectFields: ['gridWidth', 'gridHeight'],
    shiftedDiagnosticBands: ['minimumFeatureWidthCells', 'smallIslandDetectionCells', 'samplingTolerance'],
    neutralMeaning: 'Default 2:1 equirectangular grid.',
    lowExtremeMeaning: 'Lower detail; diagnostics should widen cell-count tolerances only.',
    highExtremeMeaning: 'Higher detail; narrower cell-level features can be represented.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'SEA_LEVEL_CURRENT',
    label: 'Sea Level (current)',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['seaLevel'],
    realWorldFunction: 'Currently behaves as Water Inventory / Ocean Coverage by targeting land fraction.',
    allowedLayers: ['WATER_SURFACE_STATE', 'OCEAN_BATHYMETRY', 'CLIMATE_HYDROLOGY_BIOME'],
    allowedDirectFields: ['targetLandFraction', 'seaLevel', 'isWater', 'oceanDepthClass'],
    shiftedDiagnosticBands: ['landCoverage', 'oceanCoverage', 'shelfExposure', 'coastDensity', 'oceanDepthDistribution', 'islandShare'],
    neutralMeaning: 'Earthlike ocean/land balance.',
    lowExtremeMeaning: 'Dry planet, exposed shelves, smaller seas, broad lowlands exposed.',
    highExtremeMeaning: 'Flooded planet, submerged shelves, exposed land mostly highlands/arcs/cratons/hotspots.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
    targetReplacementIds: ['WATER_INVENTORY', 'SEA_LEVEL_OFFSET'],
  },
  {
    id: 'PLATE_ACTIVITY_CURRENT',
    label: 'Plate Activity (current)',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['plateActivity'],
    realWorldFunction: 'Currently mixes tectonic energy, plate motion, boundary feature strength, plate spacing, and macro-structure.',
    allowedLayers: ['WORLD_CORE_HEAT', 'MANTLE_VOLATILE_HOTSPOT', 'PLATE_SHELL', 'BOUNDARY_FEATURES', 'TERRAIN_RESPONSE'],
    allowedDirectFields: ['plateVelocityMagnitude', 'boundaryFeatureStrength', 'upliftRate', 'volcanicActivity'],
    shiftedDiagnosticBands: ['boundaryFeatureIntensity', 'featureSupportedExtremeShare', 'ridgeRelief', 'trenchRelief', 'mountainRelief', 'slopeP95Tolerance'],
    neutralMeaning: 'Active but Earthlike tectonics: clear feature-backed ridges, trenches, arcs, mountain belts, and transforms.',
    lowExtremeMeaning: 'Calmer tectonic planet: slower motion, weaker feature relief, fewer active volcanic/rift/trench extremes.',
    highExtremeMeaning: 'High-energy tectonic planet: stronger feature-backed relief and deformation, not stronger raw plate seams.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
    targetReplacementIds: ['TECTONIC_ENERGY', 'PLATE_FRAGMENTATION', 'BOUNDARY_COMPLEXITY'],
  },
  {
    id: 'CONTINENT_COUNT_CURRENT',
    label: 'Continent Count (current)',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['continentCount'],
    realWorldFunction: 'Currently mixes continental assembly, continental fragmentation, plate count, landmass count, and land fraction adjustment.',
    allowedLayers: ['CONTINENTAL_MORPHOLOGY', 'WATER_SURFACE_STATE', 'DIAGNOSTICS'],
    allowedDirectFields: ['continentality', 'continentCoreCount', 'shelfHaloCount', 'landmassTarget'],
    shiftedDiagnosticBands: ['landmassCount', 'largestLandmassShare', 'continentalityComponentCount', 'shelfHaloCount', 'coastDensity'],
    neutralMeaning: 'Several Earthlike continental masses, not a perfect supercontinent and not random confetti.',
    lowExtremeMeaning: 'Fewer larger continental assemblies / supercontinent tendency.',
    highExtremeMeaning: 'More continental fragments, separated landmasses, shelf/margin complexity.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
    targetReplacementIds: ['CONTINENTAL_ASSEMBLY', 'CONTINENTAL_FRAGMENTATION', 'PLATE_FRAGMENTATION'],
  },
  {
    id: 'PLANET_AGE_CURRENT',
    label: 'Planet Age (current)',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['planetAge'],
    realWorldFunction: 'Currently mixes thermal age, crust age, tectonic maturity, terrain sharpness, and surface maturity.',
    allowedLayers: ['WORLD_CORE_HEAT', 'CRUST_MATERIAL', 'TERRAIN_RESPONSE', 'SURFACE_PROCESS'],
    allowedDirectFields: ['surfaceAge', 'crustAge', 'thermalAge', 'heatFlowIndex'],
    shiftedDiagnosticBands: ['crustAgeSpread', 'volcanicActivityFrequency', 'surfaceMaturity', 'erosionMaturity', 'stableCratonShare'],
    neutralMeaning: 'Mature Earthlike planet with active but stable geology and meaningful surface maturity.',
    lowExtremeMeaning: 'Young/hot planet: more volcanism, younger crust, rougher active terrain.',
    highExtremeMeaning: 'Older/cooler planet: stable crust, lower heat flow, more erosion/sediment maturity unless tectonics overrides.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
    targetReplacementIds: ['PLANET_THERMAL_AGE', 'SURFACE_MATURITY'],
  },
  {
    id: 'EROSION_INTENSITY_CURRENT',
    label: 'Erosion Intensity (current)',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['erosionIntensity'],
    realWorldFunction: 'Currently acts as smoothing, texture, strait, and coast-breakup strength; target meaning is surface maturity/erosion strength.',
    allowedLayers: ['SURFACE_PROCESS', 'TERRAIN_RESPONSE', 'HYDROLOGY_SOIL'],
    allowedDirectFields: ['erosionStrength', 'sedimentFill', 'slopeSoftening', 'drainageMaturity'],
    shiftedDiagnosticBands: ['slopeP95', 'singleCellSpikeShare', 'landReliefLoss', 'featureReliefPreservation', 'sedimentFill'],
    neutralMeaning: 'Earthlike mature erosion: reduce noise without erasing tectonic relief.',
    lowExtremeMeaning: 'Rougher/younger surface, sharper relief, less sediment fill.',
    highExtremeMeaning: 'Older/smoother surface, more sediment-filled basins, softer slopes.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
    targetReplacementIds: ['SURFACE_MATURITY', 'EROSION_STRENGTH', 'SEDIMENT_FILL'],
  },
  {
    id: 'AXIS_TILT',
    label: 'Axis Tilt',
    status: 'current',
    visibility: 'advanced',
    currentParamKeys: ['axisTilt'],
    realWorldFunction: 'Axial tilt / seasonality / latitudinal climate structure.',
    allowedLayers: ['CLIMATE_FORCING', 'ATMOSPHERIC_CIRCULATION', 'BIOME_ECOLOGY'],
    allowedDirectFields: ['seasonalityStrength', 'latitudeTemperatureGradient', 'snowlineBias'],
    shiftedDiagnosticBands: ['latitudeTemperatureGradient', 'snowLatitudeDistribution', 'polarSnowIceShare', 'biomeLatitudeDistribution', 'desertBeltMigration'],
    neutralMeaning: 'Earthlike broad latitude climate and seasonality.',
    lowExtremeMeaning: 'Weaker seasons, more stable climate bands.',
    highExtremeMeaning: 'Strong seasons, more dramatic snow/desert/grassland transitions and polar/equatorial contrasts.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'CLIMATE_VARIABILITY',
    label: 'Climate Variability',
    status: 'current',
    visibility: 'advanced',
    currentParamKeys: ['climateVar'],
    realWorldFunction: 'Regional temperature/rainfall variation and climate patchiness.',
    allowedLayers: ['CLIMATE_FORCING', 'ATMOSPHERIC_CIRCULATION', 'BIOME_ECOLOGY'],
    allowedDirectFields: ['temperatureVariance', 'rainfallVariance', 'biomePatchiness'],
    shiftedDiagnosticBands: ['biomeDiversity', 'rainfallVariance', 'temperatureVariance', 'snowDistributionVariance'],
    neutralMeaning: 'Earthlike regional climate variation.',
    lowExtremeMeaning: 'Smooth latitude-dominated climate bands.',
    highExtremeMeaning: 'Patchier, more regionally varied climate.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'MOISTURE_LEVEL',
    label: 'Moisture Level',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['moistureLevel'],
    realWorldFunction: 'Global atmospheric/oceanic moisture availability, constrained by water inventory, atmosphere retention, and solar input.',
    allowedLayers: ['CLIMATE_FORCING', 'MOISTURE_TRANSPORT', 'HYDROLOGY_SOIL', 'BIOME_ECOLOGY'],
    allowedDirectFields: ['rainfallMean', 'soilMoisture', 'riverDensity', 'wetBiomeShare', 'dryBiomeShare'],
    shiftedDiagnosticBands: ['rainfallMean', 'riverDensity', 'wetBiomeShare', 'dryBiomeShare', 'snowAmountWhenCold'],
    neutralMeaning: 'Earthlike moisture distribution.',
    lowExtremeMeaning: 'Dry planet: deserts, sparse rivers, lower vegetation density.',
    highExtremeMeaning: 'Wet planet: forests/wetlands, more rivers, more precipitation where climate allows.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'TEMPERATURE_OFFSET_CURRENT',
    label: 'Temperature Offset (current)',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['temperatureOffset'],
    realWorldFunction: 'Temporary global heat control until Solar Input + Greenhouse + Albedo exist.',
    allowedLayers: ['STELLAR_ENERGY', 'CLIMATE_FORCING', 'BIOME_ECOLOGY'],
    allowedDirectFields: ['temperatureMean', 'snowlineBias', 'effectiveHeatIndex'],
    shiftedDiagnosticBands: ['meanTemperature', 'snowLandFraction', 'biomeClimateBands', 'polarElevationSnowConsistency'],
    neutralMeaning: 'Earthlike global temperature baseline.',
    lowExtremeMeaning: 'Cold world: more snow/ice, lower snowline, cooler biomes.',
    highExtremeMeaning: 'Hot world: less snow/ice, hotter biomes, more arid heat stress if moisture is low.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
    targetReplacementIds: ['SOLAR_INPUT', 'GREENHOUSE', 'ALBEDO'],
  },
  {
    id: 'SEED',
    label: 'Seed',
    status: 'current',
    visibility: 'basic',
    currentParamKeys: ['seed'],
    realWorldFunction: 'Deterministic realization of the same physical parameter intent.',
    allowedLayers: ['ALL_NOISE_REALIZATION'],
    allowedDirectFields: ['randomSeed'],
    shiftedDiagnosticBands: [],
    neutralMeaning: 'Same sliders should target same adjusted contract across seeds.',
    lowExtremeMeaning: 'Not applicable.',
    highExtremeMeaning: 'Not applicable.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },

  // Target/future controls.
  {
    id: 'PLANET_PROFILE',
    label: 'Planet Profile',
    status: 'target',
    visibility: 'basic',
    currentParamKeys: [],
    realWorldFunction: 'Selects the valid planet/interior stack before plates or terrain run.',
    allowedLayers: ['PLANET_PROFILE'],
    allowedDirectFields: ['planetProfile', 'validLayerStack', 'surfaceSupportMode'],
    shiftedDiagnosticBands: ['validPlanetProfileLayerSet'],
    neutralMeaning: 'Earthlike Rocky for Earthlike mode.',
    lowExtremeMeaning: 'Not a numeric slider.',
    highExtremeMeaning: 'Alien/fantasy profiles can choose alternate legal stacks.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'PLANET_SIZE_GRAVITY',
    label: 'Planet Size / Gravity',
    status: 'target',
    visibility: 'advanced',
    currentParamKeys: [],
    realWorldFunction: 'Sets radius/density/mass/gravity/escape velocity before terrain and atmosphere expectations.',
    allowedLayers: ['PLANET_SIZE_GRAVITY', 'ATMOSPHERE_RETENTION', 'TERRAIN_RESPONSE', 'EXPORT'],
    allowedDirectFields: ['planetRadiusEarth', 'planetDensityEarth', 'planetMassEarth', 'surfaceGravityEarth', 'escapeVelocityEarth', 'reliefGravityScale'],
    shiftedDiagnosticBands: ['reliefHeightTolerance', 'slopeTolerance', 'atmosphereRetention', 'hydrologyPersistence', 'exportHeightScaling'],
    neutralMeaning: 'Earthlike radius/density/gravity.',
    lowExtremeMeaning: 'Dwarf/small body: low gravity, sharper relief allowed, atmosphere retention risk.',
    highExtremeMeaning: 'Super-Earth: higher gravity, smoother/lower relative relief, stronger atmosphere retention.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'SOLAR_INPUT',
    label: 'Solar Input',
    status: 'target',
    visibility: 'basic',
    currentParamKeys: [],
    realWorldFunction: 'Incoming stellar energy: star luminosity divided by orbital distance squared.',
    allowedLayers: ['STELLAR_ENERGY', 'CLIMATE_FORCING', 'MOISTURE_TRANSPORT', 'BIOME_ECOLOGY'],
    allowedDirectFields: ['starLuminositySun', 'orbitalDistanceAU', 'stellarFluxEarth', 'effectiveHeatIndex', 'evaporationPotential'],
    shiftedDiagnosticBands: ['meanTemperature', 'evaporationPotential', 'snowIceShare', 'biomeTemperatureBands', 'rainfallPotential'],
    neutralMeaning: '0.90-1.10 Earthlike stellar flux.',
    lowExtremeMeaning: 'Cold/frozen world unless greenhouse compensates.',
    highExtremeMeaning: 'Warm/hot world with more evaporation and heat stress unless albedo/greenhouse/water balance compensate.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'GREENHOUSE',
    label: 'Greenhouse',
    status: 'target',
    visibility: 'advanced',
    currentParamKeys: [],
    realWorldFunction: 'Atmospheric heat retention independent of orbital stellar flux.',
    allowedLayers: ['STELLAR_ENERGY', 'ATMOSPHERE_RETENTION', 'CLIMATE_FORCING'],
    allowedDirectFields: ['greenhouseStrength', 'effectiveHeatIndex', 'surfacePressureProxy'],
    shiftedDiagnosticBands: ['meanTemperature', 'snowIceShare', 'evaporationPotential', 'rainfallPotential'],
    neutralMeaning: 'Earthlike heat retention.',
    lowExtremeMeaning: 'Thin/low greenhouse: colder for same solar input.',
    highExtremeMeaning: 'Thick/high greenhouse: warmer for same solar input, stronger water-cycle potential if water exists.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'ALBEDO',
    label: 'Albedo',
    status: 'target',
    visibility: 'advanced',
    currentParamKeys: [],
    realWorldFunction: 'Fraction of incoming energy reflected away before heating climate.',
    allowedLayers: ['STELLAR_ENERGY', 'CLIMATE_FORCING', 'FINAL_RENDER'],
    allowedDirectFields: ['albedo', 'surfaceAbsorbedFlux', 'effectiveHeatIndex'],
    shiftedDiagnosticBands: ['meanTemperature', 'snowIceShare', 'cloudIceCooling'],
    neutralMeaning: 'Earthlike reflectivity.',
    lowExtremeMeaning: 'Dark absorber: hotter for same solar input.',
    highExtremeMeaning: 'Bright/icy/cloudy reflector: cooler for same solar input.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'CORE_HEAT',
    label: 'Core Heat',
    status: 'target',
    visibility: 'advanced',
    currentParamKeys: [],
    realWorldFunction: 'Deep internal thermal engine that feeds mantle activity, volcanism, rifts, hotspots, and tectonic vigor.',
    allowedLayers: ['WORLD_CORE_HEAT', 'MANTLE_VOLATILE_HOTSPOT', 'PLATE_SHELL', 'BOUNDARY_FEATURES', 'CRUST_MATERIAL'],
    allowedDirectFields: ['coreHeat', 'mantleHeat', 'radiogenicHeat', 'primordialHeat', 'heatFlowIndex', 'tidalHeatingIndex'],
    shiftedDiagnosticBands: ['volcanicActivityFrequency', 'riftLikelihood', 'ridgeStrength', 'hotspotActivity', 'crustHeat'],
    neutralMeaning: 'Mature Earthlike heat flow.',
    lowExtremeMeaning: 'Cold/stagnant world: weaker tectonics and volcanism.',
    highExtremeMeaning: 'Young/hot or Io-like world: high volcanism and instability, terrain still feature/material-driven.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
  {
    id: 'VOLATILE_INVENTORY',
    label: 'Volatile Inventory',
    status: 'target',
    visibility: 'advanced',
    currentParamKeys: [],
    realWorldFunction: 'Internal and surface volatile supply for outgassing, atmosphere, water/ice, geysers, and volatile-pressure worlds.',
    allowedLayers: ['MANTLE_VOLATILE_HOTSPOT', 'ATMOSPHERE_RETENTION', 'WATER_SURFACE_STATE', 'CLIMATE_HYDROLOGY_BIOME'],
    allowedDirectFields: ['volatileReservoir', 'volatilePressure', 'outgassingPotential', 'volatileAtmosphereSupply', 'waterInventory'],
    shiftedDiagnosticBands: ['atmosphereMassProxy', 'waterInventory', 'geyserVentFeatureShare', 'wetBiomePotential'],
    neutralMeaning: 'Earthlike volatile inventory for selected profile.',
    lowExtremeMeaning: 'Dry/thin volatile world.',
    highExtremeMeaning: 'Volatile-rich/outgassing/pressure world, still requiring support shell for land.',
    forbiddenAuthorityRelaxations: HARD_FORBIDDEN,
  },
];

export function getSliderContract(id: string): SliderContract | undefined {
  return GENERATE_SLIDER_CONTRACTS.find((entry) => entry.id === id);
}

export function listCurrentSliderContracts(): readonly SliderContract[] {
  return GENERATE_SLIDER_CONTRACTS.filter((entry) => entry.status === 'current');
}

export function listTargetSliderContracts(): readonly SliderContract[] {
  return GENERATE_SLIDER_CONTRACTS.filter((entry) => entry.status === 'target');
}
