import { mkdirSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  DEFAULT_GENERATE_DIAGNOSTIC_HEIGHT,
  DEFAULT_GENERATE_DIAGNOSTIC_SEEDS,
  DEFAULT_GENERATE_DIAGNOSTIC_WIDTH,
  runMultiSeedGenerateDiagnostics,
  type AblationStageId,
  type MultiSeedGenerateDiagnostics,
  type StageDeltaRanking,
} from '../src/core/worldGenerateMultiSeedDiagnostics';

const OUTPUT_DIR = 'diagnostics-output';
const JSON_PATH = `${OUTPUT_DIR}/generate-multiseed-latest.json`;
const MARKDOWN_PATH = `${OUTPUT_DIR}/generate-multiseed-latest.md`;

const ABLATIONS: AblationStageId[] = [
  'PLATE_BOUNDARY_FEATURE_TERRAIN',
  'SKELETON_ELEVATION',
  'QUALITY_PASS',
  'ISOSTATIC_TERRAIN_RESPONSE',
  'CRUST_PROVINCE_DELTA',
  'OCEAN_BATHYMETRY_SMOOTHING',
];

describe('Generate diagnostics report runner', () => {
  it('writes a human-readable Generate diagnostics report', () => {
    const result = runMultiSeedGenerateDiagnostics({ ablations: ABLATIONS });
    mkdirSync(OUTPUT_DIR, { recursive: true });
    writeFileSync(JSON_PATH, JSON.stringify(result, null, 2));
    writeFileSync(MARKDOWN_PATH, renderMarkdownReport(result));

    printConsoleSummary(result);

    expect(result.runs.length).toBe(DEFAULT_GENERATE_DIAGNOSTIC_SEEDS.length);
    expect(result.topSuspectStages.length).toBeGreaterThan(0);
  }, 60_000);
});

function printConsoleSummary(result: MultiSeedGenerateDiagnostics): void {
  console.log('\nWorldWright Generate diagnostics written:');
  console.log(`- ${MARKDOWN_PATH}`);
  console.log(`- ${JSON_PATH}`);
  console.log('\nTop suspects:');
  for (const stage of result.topSuspectStages) console.log(`- ${stage}`);
  console.log('\nTop plate imprint increases:');
  for (const row of top(result.rankings.plateImprintIncreases)) console.log(formatRankingLine(row));
  console.log('\nTop province imprint increases:');
  for (const row of top(result.rankings.provinceImprintIncreases)) console.log(formatRankingLine(row));
  console.log('\nTop relief decreases:');
  for (const row of top(result.rankings.reliefDecreases)) console.log(formatRankingLine(row));
}

function renderMarkdownReport(result: MultiSeedGenerateDiagnostics): string {
  const ablations = summarizeAblations(result);
  const morphology = averageMetric(result.runs.map((run) => run.finalMorphology));
  const hydrology = averageMetric(result.runs.map((run) => run.finalHydrology));
  const leak = averageMetric(result.runs.map((run) => run.finalCauseLeak));

  return [
    '# WorldWright Generate Multi-seed Diagnostics',
    '',
    'Generated by `npm run diagnostics:generate`.',
    '',
    'Diagnostics only. This report does not change terrain generation, renderer behavior, schema, sea level, Generate UI visuals, or pipeline order.',
    '',
    '## Run settings',
    '',
    `- Grid: ${DEFAULT_GENERATE_DIAGNOSTIC_WIDTH}×${DEFAULT_GENERATE_DIAGNOSTIC_HEIGHT}`,
    `- Seeds: ${result.seeds.map((seed) => `\`${seed}\``).join(', ')}`,
    `- Ablations: ${ABLATIONS.map((stage) => `\`${stage}\``).join(', ')}`,
    '',
    '## Final ranked suspects',
    '',
    result.topSuspectStages.length ? result.topSuspectStages.map((stage, index) => `${index + 1}. \`${stage}\``).join('\n') : '_No suspects returned._',
    '',
    '## Stage ranking summary',
    '',
    '### Plate imprint increases',
    rankingTable(result.rankings.plateImprintIncreases),
    '',
    '### Province imprint increases',
    rankingTable(result.rankings.provinceImprintIncreases),
    '',
    '### Skeleton imprint increases',
    rankingTable(result.rankings.skeletonImprintIncreases),
    '',
    '### Relief decreases',
    rankingTable(result.rankings.reliefDecreases),
    '',
    '### Fragment increases',
    rankingTable(result.rankings.fragmentIncreases),
    '',
    '### Fragment repairs',
    rankingTable(result.rankings.fragmentRepairs),
    '',
    '### Worst repair benefit vs imprint cost',
    rankingTable(result.rankings.worstRepairBenefitVsImprintCost),
    '',
    '## Per-seed suspect table',
    '',
    perSeedTable(result),
    '',
    '## Ablation summary',
    '',
    ablationTable(ablations),
    '',
    '## Morphology summary',
    '',
    metricTable({
      landHeightStdDev: morphology.landHeightStdDev,
      oceanDepthStdDev: morphology.oceanDepthStdDev,
      slopeMean: morphology.slopeMean,
      slopeP95: morphology.slopeP95,
      roughnessMean: morphology.roughnessMean,
      coastComplexity: morphology.coastComplexity,
      landPatchCount: morphology.landPatchCount,
      largestLandmassShare: morphology.largestLandmassShare,
      shorelineJaggedness: morphology.shorelineJaggedness,
    }),
    '',
    '## Hydrology summary',
    '',
    metricTable({
      riverCount: hydrology.riverCount,
      riverCellCount: hydrology.riverCellCount,
      averageRiverLength: hydrology.averageRiverLength,
      maxRiverLength: hydrology.maxRiverLength,
      percentRiversReachingOcean: hydrology.percentRiversReachingOcean,
      inlandDeadEndRiverCount: hydrology.inlandDeadEndRiverCount,
      flowAccumulationConcentration: hydrology.flowAccumulationConcentration,
      basinCount: hydrology.basinCount,
      tinyIsolatedDrainageArtifacts: hydrology.tinyIsolatedDrainageArtifacts,
    }),
    '',
    '## Cause-leak summary',
    '',
    metricTable({
      plateHeightJump: leak.plateHeightJump,
      provinceHeightJump: leak.provinceHeightJump,
      skeletonHeightJump: leak.skeletonHeightJump,
      plateTopGradientShare: leak.plateTopGradientShare,
      provinceTopGradientShare: leak.provinceTopGradientShare,
      skeletonTopGradientShare: leak.skeletonTopGradientShare,
      crustThicknessCorrelation: leak.crustThicknessCorrelation,
      crustAgeCorrelation: leak.crustAgeCorrelation,
      continentalityCorrelation: leak.continentalityCorrelation,
      shelfStrengthCorrelation: leak.shelfStrengthCorrelation,
      provincePatchCount: leak.provincePatchCount,
      skeletonPatchCount: leak.skeletonPatchCount,
      heightNeighborAutocorrelation: leak.heightNeighborAutocorrelation,
      provinceNeighborAutocorrelation: leak.provinceNeighborAutocorrelation,
    }),
    '',
    '## Simple interpretation guide',
    '',
    '- If a stage repeatedly ranks high for plate/province/skeleton imprint increases, it is making hidden authority visible.',
    '- If a stage ranks high for relief decreases, it may be flattening the planet.',
    '- If an ablation improves relief or reduces imprint without topology collapse, that stage is a strong fix candidate.',
    '- If an ablation causes topology collapse, that stage may be necessary but should be made narrower or repair-only.',
    '',
  ].join('\n');
}

function top(rows: StageDeltaRanking[], count = 5): StageDeltaRanking[] {
  return rows.slice(0, count);
}

function rankingTable(rows: StageDeltaRanking[]): string {
  const body = top(rows)
    .map((row) => `| \`${row.stage}\` | ${formatNumber(row.score)} | ${row.count} |`)
    .join('\n');
  return ['| Stage | Score | Count |', '| --- | ---: | ---: |', body || '| _none_ | 0 | 0 |'].join('\n');
}

function formatRankingLine(row: StageDeltaRanking): string {
  return `- ${row.stage}: score ${formatNumber(row.score)}, count ${row.count}`;
}

function perSeedTable(result: MultiSeedGenerateDiagnostics): string {
  const rows = result.runs.map((run) => {
    const plate = topDeltaStage(run.stages, 'plateSeamHeightRatio', true);
    const province = topDeltaStage(run.stages, 'provinceSeamHeightRatio', true);
    const skeleton = topDeltaStage(run.stages, 'skeletonSeamHeightRatio', true);
    const reliefDrop = topDeltaStage(run.stages, 'landHeightStdDev', false);
    return `| \`${run.seed}\` | \`${plate.stage}\` ${formatSigned(plate.value)} | \`${province.stage}\` ${formatSigned(province.value)} | \`${skeleton.stage}\` ${formatSigned(skeleton.value)} | \`${reliefDrop.stage}\` ${formatSigned(reliefDrop.value)} |`;
  });
  return ['| Seed | Plate imprint jump | Province imprint jump | Skeleton imprint jump | Relief drop |', '| --- | --- | --- | --- | --- |', ...rows].join('\n');
}

function topDeltaStage(stages: MultiSeedGenerateDiagnostics['runs'][number]['stages'], key: keyof MultiSeedGenerateDiagnostics['runs'][number]['stages'][number]['deltaFromPrevious'], positive: boolean): { stage: string; value: number } {
  let best = { stage: 'none', value: 0 };
  for (const stage of stages.slice(1)) {
    const raw = Number(stage.deltaFromPrevious?.[key] ?? 0);
    const score = positive ? raw : -raw;
    if (score > best.value) best = { stage: stage.id, value: raw };
  }
  return best;
}

function summarizeAblations(result: MultiSeedGenerateDiagnostics): Record<string, Record<string, number>> {
  const groups = new Map<string, Array<Record<string, number>>>();
  for (const run of result.runs) {
    for (const ablation of run.ablations) {
      const rows = groups.get(ablation.skippedStage) ?? [];
      rows.push({
        landFraction: Number(ablation.deltaFromBaseline.landFraction ?? 0),
        landComponents: Number(ablation.deltaFromBaseline.landComponents ?? 0),
        mediumFragmentCount: Number(ablation.deltaFromBaseline.mediumFragmentCount ?? 0),
        relief: Number(ablation.deltaFromBaseline.landHeightStdDev ?? 0),
        plateImprint: Number(ablation.deltaFromBaseline.plateSeamHeightRatio ?? 0),
        provinceImprint: Number(ablation.deltaFromBaseline.provinceSeamHeightRatio ?? 0),
        skeletonImprint: Number(ablation.deltaFromBaseline.skeletonSeamHeightRatio ?? 0),
        topologyCollapse: ablation.topologyCollapse ? 1 : 0,
      });
      groups.set(ablation.skippedStage, rows);
    }
  }
  return Object.fromEntries(Array.from(groups, ([stage, rows]) => [stage, averageMetric(rows)]));
}

function ablationTable(groups: Record<string, Record<string, number>>): string {
  const rows = Object.entries(groups).map(([stage, row]) => `| \`${stage}\` | ${formatSigned(row.landFraction)} | ${formatSigned(row.landComponents)} | ${formatSigned(row.mediumFragmentCount)} | ${formatSigned(row.relief)} | ${formatSigned(row.plateImprint)} | ${formatSigned(row.provinceImprint)} | ${formatSigned(row.skeletonImprint)} | ${formatNumber(row.topologyCollapse)} |`);
  return ['| Skipped stage | Δ land | Δ bodies | Δ med fragments | Δ relief | Δ plate imprint | Δ province imprint | Δ skeleton imprint | Collapse |', '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |', ...rows].join('\n');
}

function metricTable(row: Record<string, number | null | undefined>): string {
  const rows = Object.entries(row).map(([k, v]) => `| ${k} | ${formatNumber(v)} |`);
  return ['| Metric | Value |', '| --- | ---: |', ...rows].join('\n');
}

function averageMetric<T extends Record<string, number | null | undefined>>(rows: T[]): Record<string, number> {
  const keys = new Set(rows.flatMap((row) => Object.keys(row)));
  const out: Record<string, number> = {};
  for (const key of keys) out[key] = mean(rows.map((row) => Number(row[key] ?? 0)));
  return out;
}

function formatNumber(value: number | null | undefined): string {
  if (value == null || !Number.isFinite(value)) return '0';
  return Math.abs(value) >= 1 ? value.toFixed(2) : value.toFixed(4);
}

function formatSigned(value: number): string {
  const v = formatNumber(value);
  return value > 0 ? `+${v}` : v;
}
